### ISSUE TITLE
TensorRT setMemoryPoolLimit error

### ISSUE THREAD

**Issue by CodeColdCook** [project-zetton/zetton-inference-tensorrt#1]
Hello! I am trying to build, but found error of TensorRT, and I found the API of `setMemoryPoolLimit` was added in 8.4. So I have to comment out the code as follows, and the error disappears.

[tensorrt_backend.cc](https://github.com/project-zetton/zetton-inference-tensorrt/blob/master/src/zetton_inference_tensorrt/backend/tensorrt/tensorrt_backend.cc)
```
  config->setMaxWorkspaceSize(options_.max_workspace_size);
// #if NV_TENSORRT_MAJOR < 8.4
//   config->setMaxWorkspaceSize(options_.max_workspace_size);
// #else
//   config->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kWORKSPACE,
//                              options_.max_workspace_size);
// #endif
```

Here is the piece of log with the error.
```
zetton-inference-tensorrt/src/zetton_inference_tensorrt/backend/tensorrt/tensorrt_backend.cc:153:11: error: ‘class nvinfer1::IBuilderConfig’ has no member named ‘setMemoryPoolLimit’
   config->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kWORKSPACE,

zetton-inference-tensorrt/src/zetton_inference_tensorrt/backend/tensorrt/tensorrt_backend.cc:153:40: error: ‘nvinfer1::MemoryPoolType’ has not been declared
   config->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kWORKSPACE,
```

Here is my environment.
`Jetson NX, R32.7.2, TensorRT8.2.1`

**Comment by corenel** [comment]
The related APIs are added in TensorRT 8.4.1, see [release notes](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-4-1).

So there exist two solutions:

1. instead of using this repo to convert ONNX to the TensorRT engine, follow the method in [this document](https://github.com/project-zetton/zetton-inference/blob/master/docs/vision/detection/yolov7.md).

2. add a minor version number checking for TensorRT, and use the old APIs for the sub-8.4 version

```diff
- #if NV_TENSORRT_MAJOR < 8
+ #if NV_TENSORRT_MAJOR < 8 || (NV_TENSORRT_MAJOR ==8 && NV_TENSORRT_MINOR < 4)
```
